services:
  backend:
    build: .
    ports:
      - "3000:3000"
<<<<<<< HEAD
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=spacecmu
      - JWT_SECRET=super_secret_key_change_this
=======
    env_file:
      - ./.env
>>>>>>> 712e08e47b3b671c3607c286d1d1ad01f8b90805
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spacecmu
    ports:
<<<<<<< HEAD
      - "5433:5432"
=======
      - "5432:5432"
>>>>>>> 712e08e47b3b671c3607c286d1d1ad01f8b90805
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
