services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=spacecmu
      - JWT_SECRET=super_secret_key_change_this
      # Public base URL - leave empty to use dynamic hostname
      # Or set to specific IP: PUBLIC_BASE_URL=http://YOUR_IP:3000
      - PUBLIC_BASE_URL=
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    volumes:
      - uploads_data:/app/public/uploads

  frontend:
    build: ../spacecmu
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      # Don't set NEXT_PUBLIC_API_BASE_URL - let browser use dynamic hostname:3000
      # Server-side (SSR) API calls use backend service name
      - API_URL=http://backend:3000
    depends_on:
      - backend
    restart: on-failure

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spacecmu
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
  uploads_data:
