const adjectives = [
  "Anonymous",
  "Silent",
  "Hidden",
  "Secret",
  "Invisible",
  "Mysterious",
  "Wandering",
  "Lost",
  "Forgotten",
  "Quiet",
  "Shadowy",
  "Whispering",
  "Crimson",
  "Azure",
  "Golden",
  "Silver",
  "Obsidian",
  "Emerald",
  "Ivory",
  "Fading",
  "Drifting",
  "Fallen",
  "Stray",
  "Wild",
  "Ancient",
  "Cosmic",
  "Solar",
  "Lunar",
  "Stellar",
  "Nebula",
  "Arctic",
  "Desert",
  "Forest",
  "Crystal",
  "Rogue",
  "Phantom",
  "Glimmering",
  "Ethereal",
  "Solitary",
];

const nouns = [
  "Panda",
  "Fox",
  "Wolf",
  "Traveler",
  "Dreamer",
  "Explorer",
  "Wanderer",
  "Spirit",
  "Ghost",
  "Echo",
  "Oracle",
  "Sphinx",
  "Nomad",
  "Voyager",
  "Tiger",
  "Dragon",
  "Phoenix",
  "Gryphon",
  "Serpent",
  "Raven",
  "Owl",
  "Hunter",
  "Ranger",
  "Mage",
  "Knight",
  "Alchemist",
  "Prophet",
  "Pilgrim",
  "Sentinel",
  "Guardian",
  "Jester",
  "Riddle",
  "Mirage",
  "Oasis",
  "Comet",
  "Meteor",
  "Abyss",
  "Nexus",
  "Vertex",
  "Cipher",
  "Relic",
  "Talisman",
];

/**
 * สุ่มสร้างชื่อ Persona ที่ไม่น่าจะซ้ำกัน
 * @returns {string} e.g., "Silent Fox 123"
 */
export function generateRandomPersonaName(): string {
  const adjective = adjectives[Math.floor(Math.random() * adjectives.length)];
  const noun = nouns[Math.floor(Math.random() * nouns.length)];
  const number = Math.floor(Math.random() * 900) + 100; // สุ่มเลข 3 หลัก

  return `${adjective} ${noun} ${number}`;
}
